### ISSUE TITLE
Unable to convert date and time into local date and time using Date.now

### ISSUE THREAD

**Issue by YashRaj9211** [YashRaj9211/expesne-tracker#1]
In the `api` directory inside `module` the `expenseSchema.js` **dateTime** element is usingdafault value as Date.now I want to convert the stored date and time to local timings which is **IST**(Indian Standard Time). [Issue here](https://github.com/YashRaj9211/expesne-tracker/blob/main/api/models/expenseSchema.js)

**Comment by MZHoffman** [comment]
Where do you want to convert it? just before displaying to the user?

Also,

how do i start backend?

**Comment by YashRaj9211** [comment]
Thankyou for replying to the issue!
I want to save the date and  time in local time zone in the **database** itself.
Sorry for the inconvenience but to run the web app run 

- `npm i` to install all the dependencies 

- `cd api` directory 

- `nodemon index.js` to run the api 

- in another terminal use `npm run dev` in main directory to start the server.
Note:- It requires MongoDB to be installed on your personal device.

**Comment by Cioraz** [comment]
Hello, So basically I should convert the date and time to IST and then insert into mongoDB right?
If positive, could you assign me the issue?

**Comment by YashRaj9211** [comment]
> Hello, So basically I should convert the date and time to IST and then insert into mongoDB right?
> If positive, could you assign me the issue?

Yes
